# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""
Data models for the AI Response Evaluation Environment — Enhanced Edition.

Four tasks:
  1. Correctness & Instruction Adherence (easy)
  2. Tone & Audience Appropriateness with structured user profiles (medium)
  3. Multi-dimensional Quality Scoring — correctness, tone, empathy, safety (hard)
  4. Multi-turn Conversation Coherence — consistent, contradictions, context_loss (ultra) [NEW]
"""

from typing import Literal, Optional
from openenv.core.env_server.types import Action, Observation
from pydantic import Field


class CodeAssessmentAction(Action):
    """Action for submitting an evaluation judgment."""

    answer: str = Field(
        ...,
        description=(
            "Task 1: 'correct|incorrect|partially-correct, reason'\n"
            "Task 2: 'appropriate|needs-adjustment|inappropriate, issue1, issue2, ...'\n"
            "Task 3: 'correctness=N, tone=N, empathy=N, safety=N' (N = 0-10)\n"
            "Task 4: 'consistent=yes|no, contradictions=N, context_loss=yes|no'"
        ),
    )


class CodeAssessmentObservation(Observation):
    """Observation with scenario, user profile, grading feedback, and analytics."""

    problem_description: str = Field(default="", description="Task instructions")
    difficulty: Literal["easy", "medium", "hard", "ultra", "adversarial"] = Field(default="easy")
    test_case_input: str = Field(default="", description="Scenario to evaluate")
    task_type: str = Field(
        default="correctness_check",
        description="One of: correctness_check, tone_appropriateness, multi_dimensional, conversation_coherence",
    )
    language: str = Field(
        default="en",
        description="Language of the scenario: en (English), hi (Hindi), es (Spanish), ta (Tamil)",
    )

    # Structured user profile (populated for tasks 2 & 3)
    user_age: Optional[int] = Field(default=None, description="User's age")
    user_mood: Optional[str] = Field(
        default=None,
        description="User's emotional state: happy, sad, frustrated, anxious, neutral, angry",
    )
    user_context: Optional[str] = Field(
        default=None,
        description="Interaction context: education, customer-support, medical, professional, casual, crisis",
    )

    expected_output: Optional[str] = Field(default=None, description="Correct answer (shown after wrong submission)")
    feedback: str = Field(default="", description="Detailed grading explanation with WHY it was wrong")
    is_correct: bool = Field(default=False)
    partial_credit: float = Field(default=0.0, description="0.0-1.0 partial score for this step")
    problems_solved: int = Field(default=0)
    current_streak: int = Field(default=0)

    # ── Per-task analytics (new) ──────────────────────────────────────
    task_completion_rate: float = Field(
        default=0.0,
        description="Fraction of this task type solved correctly so far in this episode (0.0-1.0)",
    )
    avg_partial_credit: float = Field(
        default=0.0,
        description="Running average partial credit for this task type in this episode",
    )
    hardest_missed_category: Optional[str] = Field(
        default=None,
        description="For multi_dimensional task: the dimension most frequently scored far off (correctness/tone/empathy/safety)",
    )

    # ── ACL / self-learning metadata (new) ───────────────────────────────────
    current_expert_persona: Optional[str] = Field(
        default=None,
        description="Active expert persona name: Dr. Strict | Dr. Empathy | Dr. Safety | Dr. Adversarial",
    )
    problem_generated: bool = Field(
        default=False,
        description="True when this problem was dynamically generated by the LLM (not from static bank)",
    )
    generation_difficulty_level: Optional[int] = Field(
        default=None,
        description="Difficulty level (1-5) used to generate this problem. Rises as agent accuracy improves.",
    )
    adversarial_unlocked: bool = Field(
        default=False,
        description="True once both easy and medium accuracy thresholds have been cleared this episode",
    )
